baseURL = "https://really.lol"
languageCode = "en-gb"
title = "really.lol"
theme = "reallylol"
paginate = 10
buildFuture = true
timeout = 999999
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    unsafe = true
[related]
  [[related.indices]]
    name = "tags"
    weight = 100
